project:
    machine_name: eemmcdowell
    prefix: MGM
    human_name: 'MariaGwyn''s Multisites'
    profile:
        name: lightning
        contrib: true
    local:
        protocol: http
        hostname: 'local.${project.machine_name}.dd:8083'
git:
    default_branch: master
    remotes:
        - 'eemmcdowell@svn-6098.prod.hosting.acquia.com:eemmcdowell.git'
drush:
    aliases:
        remote: '${project.machine_name}.test'
        local: self
        ci: self
    default_alias: '${drush.aliases.local}'
target-hooks:
    frontend-setup:
        dir: '${docroot}'
        command: 'echo ''No frontend setup configured.'''
    frontend-build:
        dir: '${docroot}'
        command: 'echo ''No frontend build configured.'''
    post-deploy-build:
        dir: '${deploy.dir}/docroot/profiles/contrib/lightning'
        command: 'npm run install-libraries'
    post-setup-build:
        dir: '${docroot}/profiles/contrib/lightning'
        command: 'npm run install-libraries'
import: null

