geolocation.settings:
  type: config_object
  label: 'Geolocation settings'
  mapping:
    google_map_api_key:
      type: string
      label: 'Geoogle Maps API Key'

views.style.maps_common:
  type: views_style
  label: 'Geolocation CommonMap'
  mapping:
    geolocation_field:
      type: string
      label: 'Geolocation Field'
    title_field:
      type: string
      label: 'Title Field'
    centre:
      type: sequence
      label: 'Centre Option'
      sequence:
        type: mapping
        mapping:
          weight:
            type: integer
            label: 'Weight'
          enable:
            type: boolean
            label: 'enable'
          settings:
            type: sequence
            label: 'Settings'
            sequence:
              type: string

views.field.geolocation_field:
  type: views.field.field
  label: 'Geolocation Field'

field.widget.settings.geolocation_googlegeocoder:
  type: mapping
  label: 'Geolocation Google Geocoder Widget settings'
  mapping:
    populate_address_field:
      type: boolean
      label: 'Store address'
    target_address_field:
      type: string
      label: 'Target address field name'
